### ISSUE TITLE
Open Local Page

### ISSUE THREAD

**Issue by Karlingue** [musocrat/jquery-video-lightning#12]
Hello

So you add an option for open URL, good :D but can you add an other option for open a Locale Page, it's more optimized ^^

example : f-/page.php or f-/Img/video/donald.png

^^

**Comment by musocrat** [comment]
It should be able to handle local pages now. You would simply specify them the way you suggested if the link should be relative to the root of the site. Otherwise you may need to lose the preceding slash as I did in the demo.

If you try and it doesn't work I would right-click on the iframe Chrome and inspect element to see what the src attribute is and make sure it is the right path.

Let me know if that still doesn't do it.

**Comment by Karlingue** [comment]
just need add / for racine :)

He work

**Comment by Karlingue** [comment]
ust need add /login.html for racine :)

He work

**Comment by Karlingue** [comment]
Just need add /login.html for racine :)

He work
